[theme]
primaryColor = "#ffdd00"
backgroundColor = "#040014"
secondaryBackgroundColor = "#090024"
textColor = "#c9e4ff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
